### ISSUE TITLE
postwoman-proxy-server: not found when running docker build

### ISSUE THREAD

**Issue by RodolpheGohard** [hoppscotch/proxyscotch#20]
steps:

1. Clone repo
2. `sudo docker build -t proxyscotch`
3. `sudo docker run -it proxyscotch`

the build runs fine but I get this error at run:
`sh: /etc/postwoman-proxy/out/linux-server/postwoman-proxy-server: not found`

Indeed:
```sh
computer:~/dev/proxyscotch$ sudo docker run -it proxyscotch sh
/etc/postwoman-proxy $ cd out/
/etc/postwoman-proxy/out $ cd linux-server/
/etc/postwoman-proxy/out/linux-server $ ls
proxywoman-server-linux-v0.0.1
```

I'm not sure what the best way to fix this given I don't have any go background.
I also have related questions:
* Is there an official build on docker hub ?
* If not, could you add instructions on how to build and run the docker image in README ?

**Comment by NBTX** [comment]
Ah, sorry. I renamed this project from postwoman-proxy to proxyscotch and forgot about the docker build file.
I'll go ahead and update that now.

**Comment by NBTX** [comment]
The new proxy image is now available on Docker Hub:
https://hub.docker.com/repository/docker/hoppscotch/proxyscotch
