### ISSUE TITLE
Many files contain CRLF

### ISSUE THREAD

**Issue by fweep** [hoppscotch/proxyscotch#23]
@NBTX, it turns out that there are a bunch of files in your commit that introduced CRLF, and it's breaking the build in bigger ways. For example, the binary that's built has a CR in the filename, and many of the source files do. This is a bigger change than I have time to fix right now.

**Comment by SamJakob** [comment]
Okay, I think I accidentally committed from outside WSL. I’m on vacation and don’t have access to my computer until September 5th but I can fix it then.
