### ISSUE TITLE
Create new github release due to application name change

### ISSUE THREAD

**Issue by ilsubyeega** [hoppscotch/proxyscotch#37]
Currently, the latest proxyscotch release is 0.0.1 but this release is from the proxywoman (old hoppscotch name).
This causes the hopscotch application to fail the request for proxy because cors is not allowed (only allowed in postwoman.io)

To solve this problem, I would like to request a new proxyscotch release for the GitHub release if possible.
I built my own one, In some ways, some features do not work in my release.

**Comment by SamJakob** [comment]
Will create a new release shortly.

How are you running it? Server or Desktop and on what platform?

You should however be able to update the CORS domain in some cases.

**Comment by ilsubyeega** [comment]
> Will create a new release shortly.
> 
> How are you running it? Server or Desktop and on what platform?
> 
> You should however be able to update the CORS domain in some cases.

Hello! I built the binaries from wsl (ubuntu) and used windows desktop build and windows server build at windows.
For Windows desktop, i cannot figure out how to run the application since i cannot finish cert installation progress.
Lastly for Windows Server, Ive got problem that proxy is sending 0 bodies for some requests.

For this problem, I will just wait for new release and test it. Thank you!

**Comment by SamJakob** [comment]
Sorry about that, this got lost somehow when I switched over GitHub accounts. Will get on that asap!

**Comment by SamJakob** [comment]
A release with an updated version v0.1.0 has now been published.
https://github.com/hoppscotch/proxyscotch/releases/tag/v0.1.0
