### ISSUE TITLE
something wrong in crypt.go

### ISSUE THREAD

**Issue by 17307** [hoppscotch/proxyscotch#39]
When creating a certificate, there is an error in the judgment logic that prevents key.pem from being generated, and the judgment logic of whether the file exists or not and whether the write is successful or not needs to be modified.

**Comment by SamJakob** [comment]
Can you clarify which OS this occurs on? Or is it all?

**Comment by 17307** [comment]
![image](https://user-images.githubusercontent.com/26533008/172766878-927413b2-c930-40e6-9c2b-3e49bdc6a325.png)

**Comment by SamJakob** [comment]
🤦‍♂️ Thanks lol
