### ISSUE TITLE
hi, where is the license file？

### ISSUE THREAD

**Issue by wcpaxx** [hoppscotch/proxyscotch#47]
Sorry, I can't find the license file for this project

**Comment by SamJakob** [comment]
Hi, my apologies it seems I forgot to include it.

The project is MIT Licensed, I will add the file now.

**Comment by SamJakob** [comment]
Fixed with [9946103](https://github.com/hoppscotch/proxyscotch/commit/9946103b370df7f47b325fa43cf800af81ea2818)
