### ISSUE TITLE
Missing dependency: ayatana-appindicator3-0.1

### ISSUE THREAD

**Issue by steinerkelvin** [hoppscotch/proxyscotch#48]
I got the following while building on my machine:

```
# pkg-config --cflags  -- ayatana-appindicator3-0.1
Package ayatana-appindicator3-0.1 was not found in the pkg-config search path.
Perhaps you should add the directory containing `ayatana-appindicator3-0.1.pc'
to the PKG_CONFIG_PATH environment variable
Package 'ayatana-appindicator3-0.1', required by 'virtual:world', not found
pkg-config: exit status 1
```

Made it work installing the following package on Arch:
```
sudo pacman -Sy libayatana-appindicator
```

There where multiple related packages so I needed to check the packages file lists to figure the right one. Pehaps there should be a "dependencies" doc section?

**Comment by SamJakob** [comment]
Hi,

Thanks for raising this, I had needed to grab that dependency myself but must have forgotten to put it in the README.

Also just for reference - extra dependencies can be checked in the CI pipelines file, but I will try and ensure the README lists them all!
