### ISSUE TITLE
[feature]: Support for self-hosted hoppscotch

### ISSUE THREAD

**Issue by sugureshs** [hoppscotch/proxyscotch#63]
Currently, the support is only for hoppscotch.io but not for self-hosted ones.
It would be great to have the option to configure the base URL and deploy the changes.

**Comment by SamJakob** [comment]
I believe the functionality you're looking for already exists... If you run --help on the server you should see a list of options.

- `host` (default: `localhost:9159`) -- the hostname the server should listen on.
- `token` (default: `<blank>`) -- the proxy Access Token used to restrict access to the server (feature disabled if left blank).
- `allowed-origins` (default: `*`) -- a comma separated list of allowed origins (for the Access-Control-Allow-... (CORS) headers) (use * to permit any)
- `banned-outputs` (default: `<blank>`) -- a comma separated list of values to redact from responses (feature different sabled if left blank).
- `banned-dests` (default: `<blank>`) -- a comma separated list of destination hosts to prevent access to (feature disabled if left blank).

**Comment by alkanna** [comment]
I believe this issue can be closed @SamJakob :)
