### ISSUE TITLE
An unauthorized request was made

### ISSUE THREAD

**Issue by deeeeeelan** [hoppscotch/proxyscotch#80]
```
root@server:~/proxyscotch/out/linux-server# ./proxyscotch-server-linux-amd64-v0.1.1 --host="127.0.0.1:9159" --token="XXXX"
2023/11/16 06:30:19 Starting proxy server...
2023/11/16 06:30:19 [ready=true] Listening on http://127.0.0.1:9159/
2023/11/16 06:30:24 An unauthorized request was made.
2023/11/16 06:31:48 An unauthorized request was made.
```
My first time setup proxyscotch. How can i ensure that my request was authorized from hoppscotch.io ? i have been getting this error and not sure how to plug in the token value on the hoppscotch.io web. When I removed the token its working fine though. Sorry cause not that familiar with proxyscotch.

**Comment by SamJakob** [comment]
It seems for some reason that the main Hoppscotch application has removed support for specifying the access token for the server. A ticket needs to be made over there (https://github.com/hoppscotch/hoppscotch) to re-add support.

**Comment by deeeeeelan** [comment]
ok sure. thanks for your fast reply. will close this issue for now.
